import jsPDF from 'jspdf';

export const generateRecipePDF = (recipe) => {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();
    const margin = 20;
    const maxLineWidth = pageWidth - margin * 2;

    // --- Header ---
    doc.setFontSize(24);
    doc.setTextColor(78, 52, 46); // #4E342E
    doc.setFont('helvetica', 'bold');

    // Title
    const title = recipe.title || 'Recipe';
    const splitTitle = doc.splitTextToSize(title, maxLineWidth);
    doc.text(splitTitle, margin, 30);

    let yPos = 30 + (splitTitle.length * 10);

    // Meta Info (Type, Author)
    doc.setFontSize(10);
    doc.setTextColor(255, 169, 77); // #FFA94D
    doc.text(`${recipe.type || 'General'} Recipe`, margin, yPos);

    const authorText = `By ${recipe.authorName || 'Chef'}`;
    const authorWidth = doc.getTextWidth(authorText);
    doc.text(authorText, pageWidth - margin - authorWidth, yPos);

    yPos += 15;

    // --- Description ---
    doc.setFontSize(12);
    doc.setTextColor(60, 60, 60);
    doc.setFont('helvetica', 'italic');
    if (recipe.description) {
        const splitDesc = doc.splitTextToSize(`"${recipe.description}"`, maxLineWidth);
        doc.text(splitDesc, margin, yPos);
        yPos += (splitDesc.length * 7) + 10;
    }

    // --- Ingredients ---
    doc.setFontSize(16);
    doc.setTextColor(78, 52, 46);
    doc.setFont('helvetica', 'bold');
    doc.text('Ingredients', margin, yPos);
    yPos += 10;

    doc.setFontSize(11);
    doc.setTextColor(0, 0, 0);
    doc.setFont('helvetica', 'normal');

    if (recipe.ingredients && recipe.ingredients.length > 0) {
        recipe.ingredients.forEach(item => {
            // Check for page break
            if (yPos > 270) {
                doc.addPage();
                yPos = 20;
            }
            doc.text(`• ${item}`, margin + 5, yPos);
            yPos += 7;
        });
    } else {
        doc.text('No ingredients listed.', margin + 5, yPos);
        yPos += 7;
    }

    yPos += 10;

    // --- Steps ---
    // Check for page break before starting steps
    if (yPos > 250) {
        doc.addPage();
        yPos = 20;
    }

    doc.setFontSize(16);
    doc.setTextColor(78, 52, 46);
    doc.setFont('helvetica', 'bold');
    doc.text('Preparation Steps', margin, yPos);
    yPos += 10;

    doc.setFontSize(11);
    doc.setTextColor(0, 0, 0);
    doc.setFont('helvetica', 'normal');

    if (recipe.steps && recipe.steps.length > 0) {
        recipe.steps.forEach((step, index) => {
            const stepPrefix = `${index + 1}. `;
            const splitStep = doc.splitTextToSize(step, maxLineWidth - 10);

            // Check for page break
            if (yPos + (splitStep.length * 7) > 280) {
                doc.addPage();
                yPos = 20;
            }

            doc.text(stepPrefix, margin, yPos);
            doc.text(splitStep, margin + 10, yPos); // Indent step text
            yPos += (splitStep.length * 7) + 5;
        });
    } else {
        doc.text('No steps listed.', margin + 5, yPos);
    }

    // Footer
    const pageCount = doc.internal.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
        doc.setPage(i);
        doc.setFontSize(8);
        doc.setTextColor(150);
        doc.text(`Page ${i} of ${pageCount} - Generated by MealMate`, pageWidth / 2, 290, { align: 'center' });
    }

    doc.save(`${title.replace(/\s+/g, '_')}_Recipe.pdf`);
};
